# test monitoring configuration

test:
  image:
    name: monitoring
    dir: develop/tests/
    version: 64feb986
global:
  isLocalEnv: false
  containerRegistry:
    path: eu.gcr.io/kyma-project
  istio:
    tls:
      secretName: istio-ingress-certs
    gateway:
      name: kyma-gateway
      namespace: kyma-system
