---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-upgrade-job
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-upgrade
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-upgrade
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-upgrade
subjects:
- kind: ServiceAccount
  name: prometheus-upgrade-job
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus-crd
data:
  alertmanager-crd.yaml: |-
        {{.Files.Get "alertmanager.crd.yaml" | printf "%s" | indent 4}}
  servicemonitor-crd.yaml: |-
        {{.Files.Get "servicemonitor.crd.yaml" | printf "%s" | indent 4}}
  podmonitor-crd.yaml: |-
        {{.Files.Get "podmonitor.crd.yaml" | printf "%s" | indent 4}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-upgrade-helper
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "10"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: prometheus-upgrade-helper
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: prometheus-upgrade-job
      restartPolicy: Never
      containers:
      - name: job
        image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
        terminationMessagePolicy: "FallbackToLogsOnError"
        command:
          - /bin/bash
          - -c
          - |
            set -e
            kubectl delete crd \
              alertmanagers.monitoring.coreos.com \
              podmonitors.monitoring.coreos.com \
              prometheuses.monitoring.coreos.com \
              prometheusrules.monitoring.coreos.com \
              servicemonitors.monitoring.coreos.com --ignore-not-found
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-init-crd-12
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
        - name: job
          image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          volumeMounts:
            - name: prometheus-crd
              mountPath: /etc/prometheus/prometheus-crd
              readOnly: true
          command: ["kubectl",  "apply", "-f", "/etc/prometheus/prometheus-crd/alertmanager-crd.yaml"]
      volumes:
        - name: prometheus-crd
          configMap:
            name: prometheus-crd
      restartPolicy: OnFailure
