---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-upgrade-job
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-upgrade
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "delete", "create", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-upgrade
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-upgrade
subjects:
- kind: ServiceAccount
  name: prometheus-upgrade-job
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus-crd
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "0"
data:
  alertmanager-crd.yaml: |-
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: servicemonitors.monitoring.coreos.com
      labels:
        app: monitoring-operator
      annotations:
        "helm.sh/hook": crd-install
    spec:
      group: monitoring.coreos.com
      names:
        kind: ServiceMonitor
        plural: servicemonitors
      scope: Namespaced
      version: v1
    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: podmonitors.monitoring.coreos.com

      labels:
        app: monitoring-operator
    spec:
      group: monitoring.coreos.com
      names:
        kind: PodMonitor
        plural: podmonitors
      scope: Namespaced
      version: v1
    ---
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: alertmanagers.monitoring.coreos.com
      labels:
        app: monitoring-operator
    spec:
      group: monitoring.coreos.com
      names:
        kind: Alertmanager
        plural: alertmanagers
      scope: Namespaced
      version: v1
---

apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-upgrade-helper-0
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "9"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: prometheus-upgrade-helper-0
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: prometheus-upgrade-job
      restartPolicy: Never
      containers:
      - name: job
        image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
        terminationMessagePolicy: "FallbackToLogsOnError"
        command:
          - /bin/bash
          - -c
          - |
            set -e
            kubectl delete crd \
              alertmanagers.monitoring.coreos.com \
              podmonitors.monitoring.coreos.com \
              prometheuses.monitoring.coreos.com \
              prometheusrules.monitoring.coreos.com \
              servicemonitors.monitoring.coreos.com --ignore-not-found

---

apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-upgrade-helper-1
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "9"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: prometheus-upgrade-helper-1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: prometheus-upgrade-job
      restartPolicy: Never
      containers:
        - name: job
          image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
          terminationMessagePolicy: "FallbackToLogsOnError"
          command:
            - /bin/bash
            - -c
            - |
              set -e
              kubectl delete serviceaccount \
                monitoring-grafana-loki --namespace kyma-system --ignore-not-found
---

apiVersion: batch/v1
kind: Job
metadata:
  name: prometheus-upgrade-helper-2
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "9"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: prometheus-upgrade-helper-2
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: prometheus-upgrade-job
      restartPolicy: Never
      containers:
        - name: job
          image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
          terminationMessagePolicy: "FallbackToLogsOnError"
          command:
            - /bin/bash
            - -c
            - |
              set -e
              kubectl delete service \
                monitoring-alertmanager \
                monitoring-prometheus --namespace kyma-system --ignore-not-found

---
        {{/*
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus-init-crd
  annotations:
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "10"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: prometheus-upgrade-job
      containers:
        - name: job
          image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
          volumeMounts:
            - name: prometheus-crd
              mountPath: /etc/prometheus/prometheus-crd
              readOnly: true
          command: ["kubectl",  "apply", "-f", "/etc/prometheus/prometheus-crd/alertmanager-crd.yaml"]
      volumes:
        - name: prometheus-crd
          configMap:
            name: prometheus-crd
      restartPolicy: OnFailure
*/}}