apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "loki.fullname" . }}
  labels:
    app: loki
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - loki.{{ .Values.global.domainName }}
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: logging-loki
        port:
          number: {{ .Values.loki.service.port  }}
    corsPolicy:
      allowOrigin:
      - "*"
      allowHeaders:
      - access-control-allow-origin
      - authorization
  gateways:
  - kyma-gateway
